version: '3'

services:

    container: &container
        build:
            target: development
            context: .
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network

    app:
        <<: *container
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network

    db:
        image: mysql:5.7
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./vendor/__data/mysql:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
