version: "3.8"
services:
  app:
    build:
      target: base
      context: .docker/php
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
        - app-network
  
  nginx:
    build: .docker/nginx
    volumes:
      - .:/var/www
    ports:
        - "8000:80"
    networks:
        - app-network

networks:
  app-network:
    driver: bridge